"""Add categories badges schedule

Revision ID: 76011acbb73a
Revises: 2a4c9d8e6f10
Create Date: 2026-07-01 12:00:11.647736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76011acbb73a'
down_revision: Union[str, Sequence[str], None] = '2a4c9d8e6f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('proposed_by_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'cancelled', name='schedule_status', create_constraint=True), server_default='proposed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_match_id'), 'schedules', ['match_id'], unique=False)
    op.create_index(op.f('ix_schedules_proposed_by_id'), 'schedules', ['proposed_by_id'], unique=False)
    op.add_column('offers', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('average_rating', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('users', sa.Column('review_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('badges', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('wants', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wants', 'category')
    op.drop_column('users', 'badges')
    op.drop_column('users', 'review_count')
    op.drop_column('users', 'average_rating')
    op.drop_column('offers', 'category')
    op.drop_index(op.f('ix_schedules_proposed_by_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_match_id'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
